#!/usr/bin/env python3
"""
Creating Async Generator using random module
"""
import asyncio
import random
from typing import AsyncGenerator


async def async_generator() -> AsyncGenerator[int, None]:
  """
    Corotine which asynchronously yields 10 random integer in the given range

    Yields:
        int: Number(random) between range(0, 10)

    Raises:
        None

    Returns:
        None
    """
   try:
        for number in range(10):
            await asyncio.sleep(1)
            yield random.randint(0, 10)
    except GeneratorExit:
        pass

async def main() -> None:
    """
    Iterate asyncronously over numbers(random) generated by async_generator

    Args:
        None

    Return:
          None
    """
    async for number in async_generator():
        print(number)

asyncio.run(main())
